Fiver.Security.AzureAdB2C/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Fiver.Security.AzureAdB2C.Controllers
{
    //[Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Fiver.Security.AzureAdB2C/Controllers/SecurityController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;

namespace Fiver.Security.AzureAdB2C.Controllers
{
    public class SecurityController : Controller
    {
        public IActionResult Login()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "B2C_1_sign_in");
        }

        [HttpPost]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            var scheme = User.FindFirst("tfp").Value;
            await HttpContext.SignOutAsync(scheme);
        }

        [Route("signup")]
        public async Task<IActionResult> SignUp()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "B2C_1_sign_up");
        }

        [Route("editprofile")]
        public IActionResult EditProfile()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "B2C_1_edit_profile");
        }
    }
}

Fiver.Security.AzureAdB2C/Views/Home/Index.cshtml
<h2>ASP.NET Core Azure AD B2C Authentication</h2>

@if (User.Identity.IsAuthenticated)
{
    <div>
        <h1>Hello @User.Identity.Name</h1>
        <ul>
            @foreach (var claim in User.Claims)
            {
                <li>
                    <em>@claim.Type</em>: @claim.Value
                </li>
            }
        </ul>
    </div>

    <form method="post" asp-controller="Security" asp-action="Logout">
        <button type="submit">Logout</button>
    </form>

    <a asp-controller="Security" asp-action="EditProfile">Edit Profile</a>
}
else
{
    <div>
        <a asp-controller="Security" asp-action="Login">Login</a> |
        <a asp-controller="Security" asp-action="SignUp">Sign Up</a>
    </div>
}